version: "3.9"
   
services:
  db:
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_NAME=postgres
     - POSTGRES_PASSWORD=postgres
     
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_NAME=postgres
     - POSTGRES_PASSWORD=postgres
    image: studytomo
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    
    volumes:
      - .:/django_proj
    ports:
      - "8000:8000"
 